### ISSUE TITLE
hiera-mysql - truncated parameter

### ISSUE THREAD

**Issue by KarelSyrovatka** [crayfishx/hiera-mysql#15]
I want to use the module. It works well but if I search for a value that includes dots than parameter is truncated. See an example below.

hiera.yaml

---
:backends:
  - mysql

:mysql:
   :host: dbserver
   :user: dbusr
   :pass: password
   :database: db
   :port: 3306
   :query: SELECT ADSITE FROM puppetdb.ALL_SERVERS_ADSITE where servername='%{key}'
:logger: console

here is hiera lookup.

root@ubuntu:/etc/puppetlabs/code# hiera czserver1.cl.domain.com --debug
DEBUG: 2015-11-19 16:42:17 +0100: mysql_backend initialized
DEBUG: 2015-11-19 16:42:17 +0100: JDBC mode false
DEBUG: 2015-11-19 16:42:17 +0100: Using Hiera 1.x backend API to access instance of class Hiera::Backend::Mysql_backend. Lookup recursion will not be detected
DEBUG: 2015-11-19 16:42:17 +0100: mysql_backend invoked lookup
DEBUG: 2015-11-19 16:42:17 +0100: resolution type is priority
DEBUG: 2015-11-19 16:42:17 +0100: Executing SQL Query: SELECT ADSITE FROM puppetdb.ALL_SERVERS_ADSITE where servername='czserver1'
DEBUG: 2015-11-19 16:42:18 +0100: Mysql Query returned 0 rows
nil

Puppet Master OS: Ubuntu 14.04
PE: 2015.2.3

Thanks

Karel

**Comment by crayfishx** [comment]
The hiera command line now supports a .x notation for looking up specific elements of arrays and hashes.... eg

hiera some_array.0

I think this means you can no longer look up keys with dots from the command line - can you confirm if you see a problem using Puppet to look up the data rather than the hiera command line?

**Comment by crayfishx** [comment]
Are you on Puppet 3 or Puppet 4?  I think your issue is as I described from the command line - but in looking further at your issue I stumbled across a problem with dots in Puppet 4.0 and raised https://tickets.puppetlabs.com/browse/HI-485 - FYI

**Comment by KarelSyrovatka** [comment]
I am on Puppet 4. Ok, so no way to search for fqdn in MySQL.

Thanks

**Comment by crayfishx** [comment]
@KarelSyrovatka see the comment on the Puppet Labs ticket.

Do you actually have a valid use case for looking up the hostname as the actual lookup key? that doesn't seem like something you would want to do from puppet.  Variables with dots (eg: facts) used in the search hierarchy (eg: anything apart from "key") should still be fine....  Can you give me some more information as to what you are trying to do exactly

**Comment by KarelSyrovatka** [comment]
I have used hiera look up from the command line just for testing of mysql backend settings.
I created a manifest this way and I can search for fqdn if I avoid to use "key" (for fqdn)
class test  {
$srv='server1.domain.com'
$foo=hiera('server')

notify {"test1 ${foo}" :}
}
include test

Thanks for help.
