### ISSUE TITLE
Typo when checking JRUBY VERSION

### ISSUE THREAD

**Issue by tgm4883** [crayfishx/hiera-mysql#19]
There's a typo when checking for JRUBY on this line 
https://github.com/crayfishx/hiera-mysql/blob/master/lib/puppet/functions/hiera_mysql.rb#L23

Says VERISON instead of VERSION

This causes failures when running it in puppetserver as it tries to find mysql not jdbc/mysql

**Comment by crayfishx** [comment]
@tgm4883 thanks for spotting this - we're still trying to figure out how to write rspec tests around hiera 5 backends that would stop silly errors like this making it through :(

I'll roll in a fix asap this morning

**Comment by crayfishx** [comment]
Thanks @tgm4883 - FYI this has been released as 3.0.1
